#Catppuccin mocha colorscheme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

#Font settings
[font]
size = 13.0

[font.bold]
family = "DejaVuSansMNerdFont"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansMNerdFont"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansMNerdFont"
style = "Italic"

[font.normal]
family = "DejaVuSansMNerdFont"
style = "Regular"

#Setting up transparency
[window]
opacity = 0.8

#Line cursor
[cursor]
style = "Beam"
