# Notification daemon
exec-once = swaync &

# Topbar
exec-once = waybar & 

# Wallpaper
exec-once = hyprpaper &

# Cool brightness and volume up/down notification client
exec-once = swayosd-server & 

# Polkit agent
exec-once = hyprpolkitagent &

# Idler
exec-once = hypridle &

# Bluetooth gesture client
exec-once = mpris-proxy &
