# Notification daemon
exec-once = swaync &

# Topbar
exec-once = waybar & 

# Wallpaper
exec-once = hyprpaper &

# Cool brightness and volume up/down notification client
exec-once = swayosd-server & 

# Polkit agent
exec-once = systemctl --user start hyprpolkitagent

# Idler
exec-once = hypridle &
