# General
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Wayland prioritization for apps
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb

# XDG specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# NVIDIA
env = GBM_BACKEND,nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
