input {
    # Only works if you dont have multiple devices
    # kb_layout = es,us
    numlock_by_default = true
    follow_mouse = 1
    mouse_refocus = false

    # Default mouse sensitivity, removes mouse accel
    sensitivity = 0

    touchpad {
        #Makes it so that touchpad is not reversed
        natural_scroll = true 
    }
}

# Behaviour for the mouse to focus on windows
cursor {
    no_warps = true
    persistent_warps = false
    warp_on_change_workspace = 0
}

# Default laptop keyboard with es layout
device {
  name = at-translated-set-2-keyboard
  kb_layout = es
}

# Wireless keyboard with us layout and international character bindings
device {
    name = "compx-2.4g-wireless-receiver"
    kb_layout = us
    kb_variant = altgrintl
}

# Scroll through workspaces in use with the touchpad
gesture = 3, horizontal, workspace

