# Programs to use
source = ./programs.conf

# Sets "Windows" key as main modifier
$mod = SUPER 

# Custom
bind = $mod, return, exec, $terminal
bind = $mod, x, killactive,
bind = $mod, e, exec, $fileManager
bind = $mod SHIFT, space, togglefloating,
bind = $mod, d, exec, $menu
bind = $mod, space, exec, $menu
bind = $mod, z, exec, $browser
bind = $mod, p, exec, wlogout
bind = $mod, f, fullscreen
bind = $mod, m, exec, swaync-client -t -sw
bind = $mod, w, exec, pkill waybar; waybar &

# Window management with vim bindings
bind = $mod, h, movefocus, l
bind = $mod, j, movefocus, d
bind = $mod, k, movefocus, u
bind = $mod, l, movefocus, r
bind = $mod SHIFT, h, movewindow, l
bind = $mod SHIFT, j, movewindow, d
bind = $mod SHIFT, k, movewindow, u
bind = $mod SHIFT, l, movewindow, r

# Move/resize windows with mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Scratchpad functionality
bind = $mod, S, togglespecialworkspace, scratchpad
bind = $mod SHIFT, S, movetoworkspace, special:scratchpad

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Laptop multimedia keys functionality
bindel = ,XF86AudioRaiseVolume, exec, swayosd-client --output-volume +5
bindel = ,XF86AudioLowerVolume, exec, swayosd-client --output-volume -5
bindel = ,XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bindel = ,XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle
bindel = ,XF86MonBrightnessUp, exec, swayosd-client --brightness +5
bindel = ,XF86MonBrightnessDown, exec, swayosd-client --brightness -5
bind = ,Print, exec, ~/.scripts/screenshot
bind = $mod, Print, exec, ~/.scripts/screenshot region

# Mechanical keyboard knob functionality (kinda weird bindings but it works for me)
bindel = $mod ,XF86AudioRaiseVolume, exec, swayosd-client --brightness +5
bindel = $mod ,XF86AudioLowerVolume, exec, swayosd-client --brightness -5
bind = $mod ,XF86AudioMute, exec, ~/.scripts/screenshot
bind = $mod SHIFT ,XF86AudioMute, exec, ~/.scripts/screenshot region

