# Ignore maximize requests from apps
windowrule = match:class .*, suppress_event maximize

# Borderless, workspace attached
windowrule = match:class zen, border_size 0, workspace 2
windowrule = match:class discord, border_size 0, workspace 4
windowrule = match:class Spotify, border_size 0, workspace 5
windowrule = match:class code, border_size 0, workspace 1

# Floating by default
windowrule = match:class org.gnome.Nautilus, float on, center on, size 1000 650
windowrule = match:class org.gnome.Calculator, float on, center on, size 1000 650
windowrule = match:class org.gnome.Calendar, float on, center on, size 1000 650
windowrule = match:class org.gnome.TextEditor, float on, center on, size 1000 650
windowrule = match:class blueman-manager, float on, center on, size 1000 650
windowrule = match:class org.pulseaudio.pavucontrol, float on, center on, size 1000 650
windowrule = match:class blender, float on, center on, size 1000 650
windowrule = match:class godot, float on, center on, size 1000 650

# Pinned by default
windowrule = match:title LiveSplit, opacity 0.5, pin on, border_size 0, workspace 1

# Smart gaps on
workspace = w[tv1], gapsout:0, gapsin:0

