###################
##### MODULES #####
###################

# This config is modular, each part can be found in a module file inside ./modules/

source = ./colorscheme.conf
source = ./modules/monitors.conf
source = ./modules/enviroment-variables.conf
source = ./modules/autostart.conf
source = ./modules/look-and-feel.conf
source = ./modules/animations.conf
source = ./modules/input.conf
source = ./modules/keybindings.conf
source = ./modules/workspaces.conf
