-- Generated by nwg-displays on 2026-07-19 at 19:25:54. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "0x0",
    scale = 2.000000000000001
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = true
})
